- runner.py
Executes the script to reset both input devices whenever runner.py exits (including a KeyboardInterrupt error).
> Input devices are now reset when runner.py stops running.

- agents/java_demo/java_demo_agent.py
- bot_manager.py
- grpcsupport/grpc_client.py
- requirements.txt
- rlbot.cfg
- runner.py
This will hopefully prevent CPU hogging bots from affecting their opponents.
The process priority increase should help everybody.
This includes a breaking change to grpc_client.py: You now need to call make_grpc_agent with address and port as separate params. I don't think many people are using it yet, so I'm willing to dry any and all tears.
This also requires the installation of psutil via `pip install psutil`, so we would have to update the setup instructions.
> Granting bot processes high priority, and isolating teams on separate cpus

- RLBotFramework/agents/base_independent_agent.py
- src/main/java/rlbot/Bot.java
- src/main/java/rlbot/cpp/ByteBufferStruct.java
- src/main/java/rlbot/cpp/RLBotDll.java
- src/main/java/rlbot/manager/BotManager.java
- src/main/java/rlbot/manager/BotProcess.java
- src/main/java/rlbot/py/PythonInterface.java
- src/main/java/rlbot/py/PythonServer.java
Later, we can use gradle to compile this into a jar, and include the jar in a maven publication. Java bots will be able to pull in this code as a dependency. Easy for them, and more control for us in terms of fairness and vending updates.
I've successfully tested this in-game.
> Adding framework support for java bots that communicate directly with dll.

- .gitignore
- build.gradle
Running pip during the build is unnecessary, plus jitpack can't handle it:
https://jitpack.io/com/github/RLBot/RLBot/0.0.1/build.log
The pipInstallRequirements task can still be used directly if desired.
> Don't run pip during build. Removing useless line in gitignore.

- agents/java_demo/src/rlbot/input/FullBoost.java
Psyonix moved the boost pads up from z=0 to z=64. Good prank.
> Fixing full boost detection in java demo bot.

- src/main/python/rlbot/gui/preset_editors.py
- src/main/python/rlbot/gui/presets.py
- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/utils/class_importer.py
- src/main/python/rlbot/utils/file_util.py
- src/main/python/rlbot/utils/structures/game_interface.py
- src/test/bat/can_update.bat
This will allow us to fix https://github.com/RLBot/RLBot/issues/130
I decided to move get_python_root to a new file, partly because the class_importer module can't be imported without sys.path hacking, making it a pain in the ass for this purpose.
> Adding a contains_locked_file utility

- src/main/python/rlbot/gui/design/qt_gui.py
- src/main/python/rlbot/gui/design/qt_gui.ui
- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/parsing/agent_config_parser.py
- src/main/python/rlbot/parsing/custom_config.py
The first commit removes controller passthrough from the list with options, since it was not an available feature and will not be implemented.
The second commit should add the ability to load the GUI even when rlbot.cfg is not on disk.
> GUI update fixing off-disk rlbot.cfg and remove controller_passthrough

- src/main/cpp/RLBotInterface/RLBotMessages/RLBotMessages.vcxproj
- src/main/cpp/RLBotInterface/RLBotMessages/generate-flatbuffers.bat
This will probably work better for people with spaces in their folder path.
> Generate flatbuffers via a batch file during VS build.

- src/main/python/rlbot/parsing/custom_config.py
The parameter has_values did not function properly, there could be values in there since the boolean was False. It also has no usages, except for the has_section which caused a bug in loading orange loadout from the gui.
> removed has_values from configheader

- src/main/flatbuffers/rlbot.fbs
This is a small subset of the changes in the `prediction` branch. The prediction branch is designed to have ball prediction be computed inside the core dll and then distributed to all bots.
I'm separating this out and trying to put it in now because people are trying to run ball prediction on their own without waiting for the centralized solution in the prediction branch. By making this available now, they can leverage it to make their temporary solutions in a way that will be compatible with our long-term centralized solution.
Also, the Java framework library already contains generated classes based on these fbs definitions; I must have got ahead of myself a month or two ago. This will bring our source code in master up to date with those binaries.
> Adding flatbuffer definitions to support ball predictions.

- src/main/cs/RLBotDotNet/RLBotDotNet/RLBotDotNet.csproj
- Removed unused platforms (x86/x64 debug/release)
- Fixed FlatBuffers.dll HintPath
- Reordered Reference Includes and Compile Includes in alphabetical order
- Removed FlatBuffers.pdb as a reference
> Cleaning up .csproj for RLBotDotNet

- src/main/python/rlbot/gui/preset_editors.py
- src/main/python/rlbot/gui/presets.py
- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/parsing/agent_config_parser.py
- src/main/python/rlbot/parsing/custom_config.py
Issue #194 was solved by explicitly telling we want to use 'utf8' encoding.
Issue #205 happened because realpath does not return an empty string when passing it an empty string, but instead uses the root directory, was solved by first obtaining the file path through the popup, then checking if it is a path, and after that using realpath.
> Fixes for issues #194 and #205

- src/main/python/rlbot/botmanager/bot_manager.py
- src/main/python/rlbot/botmanager/bot_manager_flatbuffer.py
- src/main/python/rlbot/botmanager/bot_manager_independent.py
- src/main/python/rlbot/botmanager/bot_manager_struct.py
- src/main/python/rlbot/setup_manager.py
Works by passing an event to BotManager which will make it reload when set.
BotManager still reloads on file modification.
Made sure it worked, when a human is playing.
You have to press 'q' to quit now.
More commands should be easy to add in the future.
> Ability to force reload of all bots by pressing 'r'. Press 'q' to quit.

- src/main/python/rlbot/gui/qt_root.py
There was a bug in the gui that made it crash when you changed an agent's name, selected another bot, and then selected the original bot again. Since there was some unintended event processing the name got partially changed again, but since it only got changed partially the gui crashed with a KeyError. Problem was solved by not making the event fire when loading an agent.
> fix the KeyError in the gui

- build.gradle
- src/main/java/rlbot/manager/BotManager.java
- src/main/java/rlbot/pyinterop/DefaultPythonInterface.java
- src/main/python/rlbot/agents/base_java_agent.py
- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/runner.py
- src/main/python/rlbot/version.py
- Java bots will now shut down when the python framework quits. This avoid some bugs where java's interface dll has stale shared memory mappings.
- Clicking the run button twice no longer causes a duplicate process disaster
- Shutting down the python framework only attempts to kill bots once, not twice.
- Improved exception handling for java bots. If there's an unhandled exception, the bot will now retire and get restarted from python. Previously it would just stop.
> Improved startup and shutdown behavior

- build.gradle
- src/main/java/rlbot/cppinterop/RLBotDll.java
32 bit JVM needs the 32 bit dll. Currently it does not get it, and just fails. If people install the default JRE they end up with a 32 bit JVM, so this is a big problem for people just hoping to try out bots.
They also get Java 8 by default. If we accidentally build the framework jar targeting java 10, they will be unable to run it.
This fixes all that.
> Using 32 bit dll when running in 32 bit JVM. Targeting 1.8.

- src/main/python/rlbot/agents/base_agent.py
- src/main/python/rlbot/gui/preset_editors.py
- src/main/python/rlbot/gui/presets.py
- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/parsing/agent_config_parser.py
- src/main/python/rlbot/utils/class_importer.py
- src/main/python/rlbot/version.py
There are lots of different cfg problems that manifest as a "Could not locate a suitable bot class" error, when really the user just has an invalid file path. This should give accurate error messages.
Also better in general to fail fast rather than confuse people with bot behavior or loadout configs that they don't expect, e.g. atba looks and not moving.
> Failing fast with specific errors when cfg files are messed up.

- src/main/python/rlbot/botmanager/helper_process_manager.py
- src/main/python/rlbot/version.py
I noticed that my Java bot would stop working sometimes, and I believe it occurred when it tried to print an exception to stderr. Works fine after this change.
> Fixing output piping for auto-run executables.

- src/main/python/rlbot/agents/base_subprocess_agent.py
- src/main/python/rlbot/gui/gui_agent.py
- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/version.py
This fixes GUI loading to not discard preset configuration files that share the same name but are located in different directories. The GUI would correctly save the rlbot.cfg file when multiple agents were added with the same name, but the loading code would overwrite all presets loaded after the initial due to matching on preset name alone.
> Fix GUI preset load and relative path problems

- src/main/python/rlbot/utils/file_util.py
People have assumed that this is the root cause of their error about 9000 times. Using logger.debug makes it not appear in the console anymore (currently we only log at info level).
> Don't scare people by logging to info about locked files.

- src/main/python/rlbot/gui/preset_editors.py
This commit only changes the order in which the items get added to the combo boxes. The order in the box being changed doesn't need any other adjustments since it checks for the text and not for the index when selecting an item.
> Sorting the customisation items in the gui

- src/main/python/rlbot/agents/base_agent.py
- src/main/python/rlbot/botmanager/bot_manager.py
- src/main/python/rlbot/utils/logging_utils.py
At the moment we can't add a handler with a level lower than the default logging_level, for example if i want to only show info logs in console but write debug level logs to a file.
We should have the level of the logger itself to be as low as possible and only set a default for the console for example.
This allows:
- adding a handler with any level.
- configuring the default handler (self.logger.handlers[0]) without changing the root logger and affecting all loggers.
> Make logging more configurable.

- src/main/python/rlbot/agents/base_subprocess_agent.py
The big one is `--rlbot-dll-directory`. This will save tourney organizers from having to futz with `PATH`
> Pass a few more options to the child process

- src/main/python/rlbot/utils/logging_utils.py
pipmain() (used in run.py on the example bots) seems to add a handler to the root logger which resutls in a doubling of logs :
```
INFO:rlbot[   game_interface.py:196 -           inject_dll() ] Injecting DLL
Injecting DLL
```
This is a fix to that.
> Fix double logs.

- src/main/cs/RLBotDotNet/RLBotDotNet/Manager/BotManager.cs
- src/main/cs/RLBotDotNet/RLBotDotNet/Properties/AssemblyInfo.cs
- src/main/cs/RLBotDotNet/RLBotDotNet/RLBotDotNet.nuspec
This adds a check to wait until the interface is initialized. This prevents RlBotDotNet from calling interface functions before the interface finished initializing.
> Interface init fix dotnet

- src/main/python/rlbot/gui/gui_agent.py
- src/main/python/rlbot/gui/qt_root.py
This resolves #305 (gui saves paths as relative) and fixes some other things like:
- Saving now assign `participant_loadout_config_X` to "None" if the agent is not using a different loadout.
- If a different loadout was set previously, adding a new bot now doesn't have that loudout. E.g. I added a bot A, changed it appearance to bot B, removed bot A, then added bot C, then bot C would be using bot B's loadout. That is no longer the case.
> Relative paths when using GUI and other various path issues related to the GUI

- src/main/python/rlbot/botmanager/bot_helper_process.py
- src/main/python/rlbot/botmanager/helper_process_manager.py
- src/main/python/rlbot/botmanager/helper_process_request.py
- src/main/python/rlbot/version.py
This is preparation for running scratch bots headless during tournaments. We need to pass though sb3 file paths, etc.
> Support for passing an options dict to BotHelperProcesses.

- src/main/python/rlbot/agents/base_agent.py
- src/main/python/rlbot/parsing/rlbot_config_parser.py
- src/main/python/rlbot/version.py
The config values are based on what @NicEastvillage added to the standard configs here: https://github.com/RLBot/RLBotPythonExample/pull/14
This will let me read the values from bundle.base_agent_config without getting an error about 'Details' not being a header. The error was happening even for bots who defined it in their config.
Also getting rid of an error message that tends to scare people.
> Adding the new Details config section to base agent configurations.

- src/main/python/rlbot/parsing/custom_config.py
- src/main/python/rlbot/parsing/directory_scanner.py
- src/main/python/rlbot/version.py
Parsing this then writing it again resulted in the second line not being indented: https://github.com/RLBot/RLBotPythonExample/blob/master/python_example/python_example.cfg#L17-L18
Subsequent parsing of the config file fails.
Also catching the ParsingError which occurs from this in the directory scanner.
> Fix for serialization of multiline values in config files

- build.gradle
- src/main/java/rlbot/cppinterop/RLBotDll.java
Related pull request for core: https://github.com/skyborgff/rlbot-core/pull/46
Now is_match_ended will be a pretty reliable indicator. It becomes true after the replay of the final goal, right before the celebration phase.
Also includes an improvement to dll initialization for java bots that might fix a few issues.
> Making java wait for interface dll initialization

- src/main/python/rlbot/agents/base_subprocess_agent.py
- src/main/python/rlbot/version.py
This is designed to fix https://github.com/RLBot/RLBot/issues/386
Self-driving car was killing the GUI when it retired. SIGTERM appears not to have that issue.
> Sending SIGTERM instead of CTRL_C_EVENT when subprocess agents retire.

- src/main/python/rlbot/gui/qt_root.py
- src/main/python/rlbot/version.py
Use case: I want to use cleopetra to generate a rlbot.cfg for a tournament match, then run run-gui.bat to tweak some things before running the match. However, the GUI complains that 
> Config file is missing the section RLBot Configuration, not loading it!
Which is true. I'm guessing that the cleopetra technique for generating the cfg omits sections that are empty. But, that section is not vital. After removing the warning, the GUI operates fine and can run the match.
> Make the GUI allow non-vital cfg sections to be missing.

- src/main/python/rlbot/botmanager/bot_manager.py
This should fix the backward incompatibility with Python 3.6 that my previous PR introduced.
> Botmanager py36 fix

- src/main/python/rlbot/setup_manager.py
This guarantees that RL can be launched on Linux, as some distros or browsers don't support Steam's browser protocol by default.
> Open RL using Popen on Linux

- src/main/python/rlbot/agents/base_agent.py
- src/main/python/rlbot/botmanager/bot_manager.py
- src/test/python/agents/atba/atba.cfg
I want to give python bots the ability to specify their maximum_tick_rate_preference.
If they set maximum_tick_rate_preference = 60 then get_output will get called at most 60 times per second.
I intend to:
- Set this value to 60 by default
- Inform our power users who want 120 that they need to update their .cfg file
This is a sensible default because the majority of our bot makers have been developing and testing on 60 Hz. I'm confident of this because few people even know how to find and modify TARLBot.ini to achieve 120.
I've tested this code pretty well. When the setting is 120, I've never observed the bot manager skipping a frame. The in-game percentages overlay responds as expected. If you set maximum_tick_rate_preference = 12, it shows a steady 10% when RLBot.exe is updating data …
> Allowing python bots to configure their preferred maximum tick rate.

- build.gradle
- src/main/java/rlbot/cppinterop/RLBotDll.java
- src/main/java/rlbot/manager/BotManager.java
- src/main/java/rlbot/render/Renderer.java
- src/test/java/rlbot/JavaExample.java
- src/test/java/rlbot/SampleBot.java
This will result in *extreme freshness*. The new packet should be delivered to java bots within a millisecond after it is made available by RLBot.exe.
This will theoretically improve the consistency and reaction time of bots. Certain things like kickoffs may need to be re-tuned by bot makers, even if they don't opt-in to 120Hz.
The specific logic was in the bot manager worked out in collaboration with Parzival.
I'm not concerned by pushing this right before the Lightfall tournament because this will not affect any bots until they are recompiled with this new code. If anybody wants to opt-out, they can set their dependency to 1.9.1: https://github.com/RLBot/RLBotJavaExample/blob/master/build.gradle#L22
> Updating the Java bot manager to use the new fresh packet feature.

- src/main/python/rlbot/botmanager/bot_manager.py
- src/main/python/rlbot/botmanager/bot_manager_flatbuffer.py
- src/main/python/rlbot/botmanager/bot_manager_struct.py
- src/main/python/rlbot/utils/structures/game_interface.py
- src/main/python/rlbot/version.py
- src/test/python/agents/flatBot/flatBot.cfg
This will result in extreme freshness. The new packet should be delivered to python bots within a millisecond after it is made available by RLBot.exe. This is similar to https://github.com/RLBot/RLBot/pull/457
This will theoretically improve the consistency and reaction time of bots. Certain things like kickoffs may need to be re-tuned by bot makers, even if they don't opt-in to 120Hz.
Unfortunately it is impossible to opt out of the *freshness* except by pinning your RLBot pip version to 1.30.0. If we see evidence that kickoffs are suffering, we can discuss ways to deal with that for the upcoming tournament.
> Updating python bot manager to use fresh packet function.

- src/main/python/rlbot/utils/process_configuration.py
Fixed by: 
- using case-insensitive match for process arguments
- checking all matching processes, not just the first one
The first commit should be enough to fix it, but I think it is still a good idea to check all matching processes rather than just the first one that we find.
> Fixed bug that led to a WrongProcessArgs error even though the args were correct.

- .gitignore
- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/utils/process_configuration.py
Rewrote the `connect_to_game` method and added an `is_rocket_league_running` method to catch when Rocket League is not running and we had started once already.
My motivation for this was that I was getting another error which made no sense when really what was wrong was the situation described above.
I also generalised the gitignore to ignore `.vscode/` folders anywhere (not just in src/main/cpp/RLBotInterface).
> Add an exception for when Rocket League is not running after the game interface has already been initialised

- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/utils/config_parser.py
This PR adds the ability for RLBot to modify TASystemSettings.ini.
By default, it does not do anything, but if the user creates a TASystemSettings.RLBot.ini file, it will back up the original TASystemSettings.ini, and merge the two settings into one file.
> Add the ability to set a separate set of TASystemSettings.ini for RLBot

- build.gradle
- src/main/java/rlbot/cppinterop/RLBotDll.java
- src/main/java/rlbot/manager/BotManager.java
Before this change, java lockstep is quite stuttery because the bot manager would often wait a bit hoping for a fresh packet when the game was paused.
> Making the Java bot manager handle lockstep better.

- src/main/python/rlbot/agents/base_agent.py
- src/main/python/rlbot/agents/base_loadout_generator.py
- src/main/python/rlbot/matchconfig/conversions.py
- src/main/python/rlbot/parsing/bot_config_bundle.py
- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/version.py
- src/test/python/agents/atba/atba.cfg
- src/test/python/agents/atba/atba_loadout.py
Gives the ability to generate your bot's loadout with a python script. This lets you choose different loadouts based on player index, randomize parts of your loadout, etc. The script is executed at the beginning of every match.
To use this feature, put a line like `loadout_generator = loadout_generator_example.py` in your bot cfg file, in the [Locations] section. Then create a python file like this:
```python
import random
from pathlib import Path
from rlbot.agents.base_loadout_generator import BaseLoadoutGenerator
from rlbot.matchconfig.loadout_config import LoadoutConfig
class SampleLoadoutGenerator(BaseLoadoutGenerator):
def generate_loadout(self, player_index: int, team: int) -> LoadoutConfig:
loadout = self.load_cfg_file(Path('appearance'), team)
if player_index == 0: …
```
> Loadout generator feature.

- src/main/java/rlbot/manager/HivemindCreator.java
- src/main/java/rlbot/manager/HivemindManager.java
- src/main/java/rlbot/manager/HivemindProcess.java
- src/main/java/rlbot/pyinterop/HiveSocketServer.java
A remake of the java `HivemindManager`. Now multiple hives can exist per team in the rare case that users wants to do that. If the user only wants a single hive, they are created exactly the same way as before:
```java
HivemindManager hivemindManager = new HivemindManager(team -> new MyHivemind(team));
HiveSocketServer server = new HiveSocketServer(port, hivemindManager);
server.start();
```
If they want to have multiple hiveminds, they must create a `HivemindCreator` that can assign hive keys to bots. A stupid example follows:
```java
HivemindManager hivemindManager = new HivemindManager(new HivemindCreator() {
@Override
public Hivemind createHivemind(int team, String hiveKey) {
return new MyHivemind(team);
}
@Override
public String assignHiveKey(int index, int team, String botName) { …
```
> Multi-hivemind support for Java (and Kotlin)

- src/main/java/rlbot/Hivemind.java
- src/main/java/rlbot/manager/BaseBotManager.java
- src/main/java/rlbot/manager/BotManager.java
- src/main/java/rlbot/manager/HivemindManager.java
- src/main/java/rlbot/manager/HivemindProcess.java
- src/main/java/rlbot/manager/IBotManager.java
- src/main/java/rlbot/pyinterop/BaseSocketServer.java
- src/main/java/rlbot/pyinterop/HiveSocketServer.java
- src/main/java/rlbot/pyinterop/SocketServer.java
- src/test/java/rlbot/JavaExample.java
This PR adds hivemind support for Java bots without breaking any backwards compatibility. Hiveminds are created very similarly to normal bots, except they they use the `HivemindManager` and the `HiveSocketServer` class:
```java
HivemindManager hivemindManager = new HivemindManager(team -> new MyHivemind(team));
HiveSocketServer server = new HiveSocketServer(port, hivemindManager);
server.start();
```
A tested example bot can be found at <https://github.com/NicEastvillage/RLBotJavaHivemindTemplate>
> Hivemind support for Java (and Kotlin)

- src/main/python/rlbot/agents/hivemind/python_hivemind.py
- set `self.team` since by default python hiveminds are separated per team and it removes the necessity to do it in `initialize_hive()`
- properly get a rendering manager with a team and index, which should make team colours work and maybe help with flickering when there are two identical hiveminds rendering
> Python Hivemind tweak

- src/main/python/rlbot/agents/hivemind/python_hivemind.py
Turns out making PRs when tired is not a great idea. I forgot to rename all appearances of `key` in PR #502 which broke Python hiveminds.
> Fixed Python Hiveminds

- src/main/python/rlbot/setup_manager.py
If a PlayerConfig is a psyonix bot then it's loadout config
was always being overwrriten. However, if the loadout was
specifically set, then we should just respect it.
> Allow Psyonix bots to be preconfigured with a loadout

- src/main/cpp/RLBotInterface/src/RLBotMessages/MessageStructs/Message.hpp
Resolves compilation error "`copying variable of type 'std::atomic_uint' (aka 'atomic<unsigned int>') invokes deleted constructor`" that appears when using `clang` (for `rlbot-rust` binding generation). There's a few questions on Stack Overflow that describe the issue in greater detail if you're curious.
Haven't tested using the [instructions from the README](https://github.com/RLBot/RLBot/blob/cbe257682f70909c27c2f1c35d9b32f7bd4cf5a3/src/main/cpp/RLBotInterface/README.md) because I don't have Visual Studio installed, sorry! It's a very minor change anyways.
> Fix currentID initialization in MessageBase constructor

- src/main/python/rlbot/gamelaunch/epic_launch.py
- src/main/python/rlbot/setup_manager.py
This will allow people to set a preference for Steam vs Epic if they have Rocket League on both. I anticipate making a change to RLBotGUI to make that more easily available.
For Epic, if they like, we will try a neat trick to harvest and incorporate a temporary key that allows login. That way they get their proper controls + camera settings. It's a little bit wild and there's a very very small chance somebody will see weird logs on an authentication server and react, so I want it to be opt-in.
> New Epic launcher technique that allows login. Ability to pass preferences on that.

- src/main/python/rlbot/agents/rlbot_runnable.py
- src/main/python/rlbot/agents/standalone/standalone_bot.py
- src/main/python/rlbot/agents/standalone/standalone_bot_config.py
- src/main/python/rlbot/parsing/bot_config_bundle.py
- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/utils/virtual_environment_management.py
- src/main/python/rlbot/version.py
- src/test/python/agents/standalone/requirements.txt
- src/test/python/agents/standalone/standalone.cfg
- src/test/python/agents/standalone/standalone.py
A standalone bot can have its own virtual environment with different package versions from other bots in the same match.
For this to work, the .cfg file needs all three of these:
```
[Locations]
supports_standalone = True
use_virtual_environment = True
requirements_file = requirements.txt
```
Before the match begins, the virtual environment will be created in a `venv` folder next to the bot cfg, and anything in the requirements file will be installed to it. When the bot is run, the venv will be used instead of the interpreter RLBot is using.
This will make it much easier for people to package / vend utility libraries because they can make breaking changes and individual bots can pin themselves to different versions and still play in the same match.
This slows down the startup process a …
> Adding virtual environment support for standalone bots.

- src/main/python/rlbot/agents/base_agent.py
- src/main/python/rlbot/matchconfig/loadout_config.py
- src/main/python/rlbot/matchconfig/match_config.py
- src/main/python/rlbot/socket/socket_manager.py
- src/main/python/rlbot/version.py
- src/test/python/agents/script/socket_match_starter.py
- src/test/python/agents/script/socket_script.py
Now that sockets is out, it's possible to bypass the dll and have Python talk directly with RLBot.exe on the socket. I've written a helper class to make this easier.
This is cool because it's the first time certain data is readily available:
- Player spectate events: When a particular player is spectated in-game, their index will be emitted
- Player input changes: When a player (bot or human) moves their controls in any way, the data is emitted
- Player stat events: Any time something happens, e.g. ball centered, hat trick, demolition, etc, an event is emitted
It can also be used to send player inputs and match starts. I haven't gotten around to implementing rendering, state setting, or quick chat, but that can be done later.
Check out the test scripts in this PR to see how it looks to an …
> Socket manager for connecting directly to RLBot.exe from Python.

- src/main/python/rlbot/utils/structures/game_interface.py
The current logic makes sure all rlbot controlled bots
are spawned and that there are no old rlbot bots hanging around.
However, if there are only humans/psyonix
bots in the config, it doesn't wait for them to spawn.
Since the spawn-id validation makes sure there are no
unexpected bots in the packets, we just need to validate
that the length of the players is matching in the
packets.
> Wait-until-valid should make wait for all players

- src/main/flatbuffers/rlbot.fbs
- src/main/python/rlbot/matchconfig/match_config.py
- src/main/python/rlbot/parsing/match_settings_config_parser.py
- src/main/python/rlbot/version.py
- currently when you try to start a match with a human it errors because humans don't have a loadout config, this should fix it
- renamed Neon_Fields to NeonFields because that's what I named it in the GUI (sorry), I think it follows the naming convention better (underscores are mostly for alternative versions)
> Fix error when starting a match with a human & rename Neon_Fields to NeonFields

- rlbot.cfg
- src/main/python/rlbot/matchconfig/match_config.py
- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/version.py
- src/test/python/agents/atba/atba.py
This is intended to fix https://github.com/RLBot/RLBot/issues/546
Bots in a match often have names like `SomeBot` and `SomeBot (2)` if there are duplicates. In the past we have always told the bot their name is `SomeBot (2)` if applicable, and bot logic has adapted to this, so we need to keep it that way. A recent change broke it, this fix will put it back.
It's good in general to have `SomeBot (2)` because the game tick packet includes bot names in some places, e.g. ball touch, and this will make it match.
If you're making a python bot and want the original name, you can do something like this:
```python
def init_match_config(self, match_config: MatchConfig):
self.logger.info(match_config.player_configs[self.index].name)
```
> Fixing issue where bots were sent their original name rather than deduped name

- src/main/python/rlbot/agents/base_script.py
- src/main/python/rlbot/setup_manager.py
- Pass the matchcomms URL as a command line argument to scripts
- Read command line arguments for matchcomms URL
Still need to do:
- Figure out if we need to close matchcomms when script terminates (and how to close it)
- Possible bug: https://discord.com/channels/348658686962696195/423167304956903428/813503008796049469
- Fix crashing during match stop (might not be directly related, but I did encounter it a lot during testing)
- Give Hiveminds access to matchcomms
> Give scripts access to matchcomms

- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/utils/virtual_environment_management.py
- Requirements won't be checked if the user doesn't have an internet connection (checked with ping to google.com)
- Requirements won't be checked multiple times (e.x. currently in a 3v3 with ABot, RLBot checks the requirements 6 times instead of 1)
This leads to some matches starting faster
> Changes to RLBot's personal virtual environments

- src/main/python/rlbot/setup_manager.py
Running RLBot through the `setup_manager_context()` results in an exception
```
File "D:\MyThings\Programming\RLBot\AutoLeague2\autoleague\match_runner.py", line 25, in run_match
with setup_manager_context() as setup_manager:
File "C:\Users\nicoesterby\AppData\Local\RLBotGUIX\Python37\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\nicoesterby\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 97, in setup_manager_context
setup_manager.connect_to_game()
File "C:\Users\nicoesterby\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 204, in connect_to_game
pref = launcher_preference or self.launcher_preference or DEFAULT_LAUNCHER_PREFERENCE
AttributeError: 'SetupManager' object has no attribute …
```
> Add launcher_preference attribute to init

- src/main/python/rlbot/setup_manager.py
My league play keeps starting up Epic and then Steam. The problem is that I use the `setup_manager_context()` which tries to connect to the game immediately. This PR adds an optional argument to `setup_manager_context()` with launcher preference.
> Add launcher preference option to setup manager context

- src/main/flatbuffers/rlbot.fbs
- src/main/python/rlbot/parsing/match_settings_config_parser.py
So, I noticed we are missing a few maps 😅 
- StarbaseArc_Aftermath - new season 5 map
- Wasteland_Night
- BeckwithPark_GothamNight
- ForbiddenTemple_Day
- UrbanCentral_Haunted - ghost hunt mode
- ChampionsField_NFL - gridiron mode
- ThrowbackStadium_Snowy
- Basin
- Corridor
- Loophole
- Galleon
- GalleonRetro
- Hourglass
- Barricade
- Colossus
I did test all of them
> Add 15 maps

- src/main/python/rlbot/utils/process_configuration.py
psutil.NoSuchProcess was not handled for one code path during launch_with_epic_login_trick which would lead to it falling back to trying to start the old way, which means it would just end up with a RL without the rlbot flags.
> fixed unhandled exception when doing epic startup trick

- src/main/python/rlbot/utils/packetanalysis/valid_packet_detector.py
This ONE SIMPLE TRICK fixes bot levitation on start!
You can trigger the bug in RLBot right now by:
Starting a match with no human and any number of bots
Join the game after launch
Using Continue and Spawn to start a new match
The bots will levitate into the air until you spectate the match, at which point you can rejoin (or you can wait out the built-in timer)
So basically, no more LAN match weirdness. I hope the single operator change explains itself. This MAY cause unintended side effects, but it's the easiest patch.
Permanent fix (idk how to do this):
Make `expected_count` and `PlayersLength()` somehow only account for bots - basically, just ignore the humans. Any actual issues that might stem from this will be edge cases where humans spawn in before bots and there are a lot of …
> Fix continue and spawn bug

- src/main/python/rlbot/gamelaunch/epic_launch.py
- src/main/python/rlbot/utils/process_configuration.py
Error can occur if the process dies between when we first saw it and grabbed the args, and then when we go to kill it where we were looking for the process via iterating all processes again and assuming success.
Fix removes the second iterating, as to reach this point we have already succeeded. If the process has already been killed we will no longer error as we can call `kill` on an already dead process without error. 
In the case it did die to have reached this point we did see it and did get the args, so no reason not to push ahead regardless.
Also includes a refactor - the is_process_running returned a bool and a process/None. It was being used in a way where the bool would be checked and then assume the process is not None based on the bool. If the bool and process is always …
> Fix for "Trouble with epic launch: 'NoneType' object has no attribute 'kill'" error

- src/main/python/rlbot/gamelaunch/epic_launch.py
Last commit not working for some, the process variable can be holding the original or restarted RL exe.
This now reverts that assumption. Instead just targets the issue the user was having with 1.62.3 where the process did not exist (so it was trying to call 'kill' on None). Instead we check that it is not None, and then also handle the case that the process may die before we kill it.
Still unsure why the RL would have dies for that user, (perhaps they had killed it?) but this fix still should give the intended outcome of the last fix: we have the args, the fact the process has dies outside of our control is OK as we have enough to continue.
> Fixed bug in last commit

- src/main/python/rlbot/botmanager/agent_metadata.py
- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/socket/socket_manager.py
- src/main/python/rlbot/training/training.py
The main part of this change is to take more care with `agent_metadata_queue`. Messages in that queue can start bots if they contain a helper process request, so it's very bad if messages from a previous match carry over to the next match somehow. Even if the bots from the previous match were properly shut down or killed, they'll be started again and cause "ghost inputs" where more than one bot process is trying to control the same bot index.
This was impacting non-python bots that rely on the helper process system, e.g. Scratch, C#, Java (and of course any bot can be impacted by the subsequent ghost inputs).
While I was in there, I made some other changes to make the training system work better for the purposes of AutoLeague type programs.
> Avoiding ghost inputs and failed bot starts when using training.

- src/main/python/rlbot/setup_manager.py
- src/main/python/rlbot/training/training.py
- src/main/python/rlbot/utils/process_configuration.py
- src/main/python/rlbot/utils/rate_limiter.py
RLBot tries to constrain each bot to a specific set of CPU cores for fairness. There was a gap in this system where a bot can spawn a child process that can use ALL cores. This is a huge advantage because the bot gets more processing power, and robs processing power from the opponent.
Now we'll periodically check for child processes that may not have been reported, and constrain them to the right cores.
> Processing agent metadata during training, registering child processes.

- src/main/python/rlbot/setup_manager.py
If a bot utilized a virtual environment, then it just wouldn't launch if the user wasn't on Windows. This, at least, should work on Windows.
> Fix launching bots with venvs on non-windows

- src/main/python/rlbot/gamelaunch/epic_launch.py
- src/main/python/rlbot/setup_manager.py
Currently we accept launcher preferences for steam vs epic. The steam choice tries steam only. The epic choice tries epic, and then falls back to steam if that fails, which causes a large amount of confusion and misery for our users.
Adding a new option (for backwards compatibility) called epic_only that does NOT fall back to steam. A separate change to RLBotGUI can rename the UI options to match the actual behaviors.
Also adding an input that RLBotGUI could use later to set the location of the Epic RocketLeague.exe file.
> Add a launcher preference for epic_only, without steam fallback

- src/main/python/rlbot/setup_manager.py
Every time a bot is launched, it will try to recreate the `venv` folder. If the folder exists, the program will only ensure it's valid and check for updates. This prevents an error that can happen when another program uses the virtual environment and RLBot tries to recreate it, throwing an error saying that `python.exe` is busy. Specifically prevented by avoiding calling the `setup_python` function in `builder.create`. Implemented for both bots and scripts.
Next, I fixed an error where RLBot could forever have `has_received_metadata_from_all_bots` return `False` because it thinks it hasn't gotten the metadata from the standalone bots. In reality, it got it before any of the normal bots, but `num_metadata_received` wasn't incremented which is the root of the issue. Incrementing that value …
> Implement fixes for standalone bots

- src/main/python/rlbot/botmanager/scratch_manager.py
- src/main/python/setup.py
- Updates usage of selenium library to work with selenium 4
- Require `selenium==4.*`
> Fix deprecated usage of selenium library in scratch manager

- src/main/python/rlbot/matchcomms/client.py
- src/main/python/rlbot/version.py
Fixes the following error, which occurs when in Python version 3.11
```
RLBotGUIX\Python311\Lib\site-packages\rlbot\matchcomms\client.py:34> exception=TypeError('Passing coroutines is forbidden, use tasks explicitly.')>
Traceback (most recent call last):
File "C:\Users\Virx\AppData\Local\RLBotGUIX\Python311\Lib\site-packages\rlbot\matchcomms\client.py", line 44, in _run_queue_io
done, pending = await io_task  # should only finish when it is cancelled in close()
^^^^^^^^^^^^^
File "C:\Users\Virx\AppData\Local\RLBotGUIX\Python311\Lib\asyncio\tasks.py", line 425, in wait
raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```
> Wrap match comm coroutines in tasks

- src/main/python/setup.py
5.8 doesn't support Python 3.11
> Fix psutil version pin
