RLBot/RLBot

AlwaysTowardsBallAgent.py
JavaAgent.py
runner.py

Since the agent class is initialized in its own thread, this avoids having to initialize the class again when getting the name bot's name.

Bot name definition outside of class

---

bot_manager.py
runner.py

To make it easier to iterate on the code.

Reload the Agent if the source has updated

---

bot_manager.py

See commit messages for details.

 Give each game_ticket_packet to the agent exactly once

---

bot_manager.py

Enables agents to close things properly.
- Worker threads
- GPU memory
- Per-run log files.

Allowed agents to retire gracefully.

---

runner.py

Autorun injector

---

RLBotFramework/utils/item_id_parser.py

Create file with id's sorted by type and ready to be posted on the wiki
https://github.com/RLBot/RLBot/wiki/Item-ID's

Uploading item_id_parser.py to get a markdown compatible item id list

---

RLBotFramework/gui/custom_agent_frame.py

https://gyazo.com/0b8a9830d1c7ef597af8c9f6da2c85a7

 Adding button linking to item id wiki on costumization ui

---

RLBotFramework/gui/custom_agent_frame.py

https://gyazo.com/0b8a9830d1c7ef597af8c9f6da2c85a7

Added button linking to Item id wiki page on bot config tab

---

agents/human/controller_input.py
agents/human/human.cfg
agents/human/human_bot.py

Add human-controlled agent

---

.gitattributes

https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

Adding a repository-level setting for line endings.

---

src/main/python/rlbot/agents/base_agent.py
src/main/python/rlbot/parsing/agent_config_parser.py
src/test/python/agents/atba/atba.py
src/test/python/agents/javaBot/javaBot.py

This should make it a bit more straightforward for bot makers to use custom configs.

Refactor custom agent configurations a bit

---

src/main/java/rlbot/cppinterop/RLBotDll.java

Makes file access threadsafe in java bot init and also makes sure that the dll is only copied once.

Java multibot init fix

---

src/main/python/rlbot/botmanager/bot_manager.py

So that the renderer can be accessed as expected from initialize_agent.

fix early invocation of initialize_agent in load_agent function

---

src/main/python/rlbot/utils/structures/game_interface.py

- Removed unecessary pass
- Toggled a logger if statement that was wrong.

game_interface.py cleanup

---

src/main/java/rlbot/manager/BotManager.java

Synchronizing java bot registration better.

---

src/main/cpp/RLBotInterface/PropertySheet.props
src/main/cpp/RLBotInterface/README.md
src/main/cpp/RLBotInterface/RLBotMessages/RLBotMessages.vcxproj

After this, it will no longer be necessary to manually run setup.bat before starting to work on the RLBotInterface solution. The core solution will benefit from this as well.

Automatically generate cpp flatbuffer headers when building RLBotMessages

---

src/main/python/rlbot/utils/rendering/rendering_manager.py

As per this issue: https://github.com/RLBot/RLBot/issues/121

Adding rendering support for Flatbuffers and ctypes vectors

---

src/main/python/rlbot/parsing/match_settings_config_parser.py
src/main/python/setup.py

Also fixing a default value for boost strength.

Making the match_settings_config_parser backwards compatible

---

src/main/python/rlbot/utils/structures/game_data_struct.py
src/main/python/rlbot/utils/structures/legacy_data_v3.py
src/main/python/setup.py

Thanks to ZeLarpMaster for the tip:
> I solved my problem by doing struct.unpack("f", struct.pack("i", timer)) which makes me think the framework thinks the timer is an int when it's a float
After doing that, the values go from 0.0 to 4.0 which makes a lot more sense

Fixing ctypes for boost timer.

---

src/main/cs/RLBotDotNet/RLBotDotNet/Bot.cs
src/main/cs/RLBotDotNet/RLBotDotNet/Interface/RLBotInterface.cs

The code is based on the Python implementation for Quick Chats.

Added support for Quick Chats in the C# Library.

---

src/main/python/rlbot/agents/base_dotnet_agent.py
src/main/python/rlbot/agents/base_java_agent.py
src/main/python/rlbot/gui/design/qt_gui.py
src/main/python/rlbot/gui/design/qt_gui.ui
src/main/python/rlbot/gui/qt_root.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/utils/process_configuration.py

Kill the bots from the gui

---

src/main/python/rlbot/utils/rendering/rendering_manager.py
src/test/python/agents/atba/atba.py

Added more colors. Here are the complete list of colors displayed ingame:

Added more built in colors to the rendering manager.

---

src/main/cs/RLBotDotNet/RLBotDotNet/Bot.cs
src/main/cs/RLBotDotNet/RLBotDotNet/Manager/BotManager.cs
src/test/cs/TestBot/ExampleBot.cs

Addresses #228 according to consensus.

Make the Bot class IDisposable

---

README.md

CrazyRambo's message in Discord made me realize I forgot to add this here

Add a Rust link in the README

---

src/main/python/rlbot/agents/base_java_agent.py
src/main/python/rlbot/botmanager/helper_process_manager.py
src/main/python/rlbot/botmanager/helper_process_request.py
src/main/python/rlbot/parsing/agent_config_parser.py
src/main/python/rlbot/parsing/custom_config.py
src/main/python/rlbot/version.py

This is mainly for smoothing out tournaments. We can do something similar for C# if desired.
Documentation here: https://github.com/RLBot/RLBotJavaExample/wiki/Auto-Launching-Java

Adding support for launching java bots automatically.

---

src/main/python/rlbot/gui/qt_root.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/utils/process_configuration.py

I've added some code to launch Rocket League when the run button is clicked if the process is not found using psutil. This includes a variable defining Rocket League's Steam gameid and process name(s). Also added a utility in process_configuration file to check if a process is running by name.

Launch game on clicking run if running process not found (QoL)

---

src/main/python/rlbot/gui/design/qt_gui.py
src/main/python/rlbot/gui/design/qt_gui.ui
src/main/python/rlbot/gui/qt_root.py
src/main/python/rlbot/parsing/match_settings_config_parser.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/utils/process_configuration.py
src/main/python/rlbot/utils/public_utils.py
src/main/python/rlbot/version.py

Updated the UI code to disable buttons that are dependent on a config file being present when no file was found. Added code to style the LineEdit box to draw attention when no config is present. All disabled buttons are re-enabled when a config is loaded.

Fixed GUI crash when no default config file was found

---

src/main/python/rlbot/utils/structures/game_data_struct.py
src/main/python/rlbot/utils/structures/struct.py

Example use:
>>> from rlbot.utils.structures.game_data_struct import Touch
>>> Touch() == Touch()
True
>>> Touch()
Touch<player_name: '', time_seconds: 0.0, hit_location: Vector3<x: 0.0, y: 0.0, z: 0.0>, hit_normal: Vector3<x: 0.0, y: 0.0, z: 0.0>>
This is intended to help newcomers explore the datastructures they're reading.
Also to allow people to more easily compare whether two structs are the same (useful for testing).

Add common python functionality to game data structs.

---

src/main/python/rlbot/parsing/custom_config.py
src/main/python/rlbot/version.py

I noticed this while working on RLBotGUI

Fixing a bug with indexed values in config objects.

---

src/main/python/rlbot/matchconfig/match_config.py
src/main/python/rlbot/parsing/agent_config_parser.py
src/main/python/rlbot/parsing/rlbot_config_parser.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/utils/structures/game_interface.py
src/main/python/rlbot/utils/structures/start_match_structures.py
src/main/python/rlbot/version.py

Match configuration refactoring to make new GUIs easier.

---

src/main/python/rlbot/agents/base_agent.py
src/main/python/rlbot/botmanager/bot_manager.py
src/main/python/rlbot/botmanager/bot_manager_flatbuffer.py
src/main/python/rlbot/botmanager/bot_manager_independent.py
src/main/python/rlbot/botmanager/bot_manager_struct.py
src/main/python/rlbot/gui/gui_agent.py
src/main/python/rlbot/gui/presets.py
src/main/python/rlbot/gui/qt_root.py
src/main/python/rlbot/matchconfig/loadout_config.py
src/main/python/rlbot/matchconfig/match_config.py
src/main/python/rlbot/parsing/agent_config_parser.py
src/main/python/rlbot/parsing/bot_config_bundle.py
src/main/python/rlbot/parsing/directory_scanner.py
src/main/python/rlbot/parsing/match_settings_config_parser.py
src/main/python/rlbot/parsing/rlbot_config_parser.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/version.py

This will allow bots to know what map they're playing on, what mutators, etc.
This also makes our python code more elegant imo.

Using MatchConfig as the main match starting interface, and passing it to bots

---

src/main/python/rlbot/agents/human/controller_input.py
src/main/python/rlbot/agents/human/human_bot.py

most of the changes are actually kipje's work from a while ago

updated controller_input

---

src/main/python/rlbot/agents/base_agent.py
src/main/python/rlbot/botmanager/bot_manager.py
src/main/python/rlbot/botmanager/bot_manager_struct.py
src/main/python/rlbot/utils/rendering/rendering_manager.py
src/main/python/rlbot/utils/structures/game_interface.py
src/main/python/rlbot/version.py

"No single corner human can occupy or experience more than a single corner at the same time during a 4-corner rotation within the 4/16 creation principle." 
\- The wisest human, Dr. Gene Ray

Clear the screen when bots retire

---

src/main/flatbuffers/rlbot.fbs

[https://thedailywtf.com/articles/What_Is_Truth_0x3f_](https://thedailywtf.com/articles/What_Is_Truth_0x3f_)

Fix comment

---

src/main/python/rlbot/training/training.py

Because only RLBot bots post metadata

Don't wait on Psyonix bots to say they're ready to start an exercise.

---

src/main/python/rlbot/botmanager/bot_manager.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/utils/structures/quick_chats.py
src/main/python/rlbot/version.py

Also Fix quickchats not shutting down on exit.

Fix quickchats creating more polling threads each reload.

---

src/main/python/rlbot/botmanager/helper_process_manager.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/training/training.py
src/main/python/rlbot/version.py

KILL. TERMINATE. EXTERMINATE. End bot processes when training is done.

---

README.md

Although I'm not sure if it's 64, or 40 bots?

Change the read-me to say it can support 64 bots

---

src/main/cpp/RLBotInterface/BallPrediction/BallPrediction.cpp
src/main/cpp/RLBotInterface/InterfaceTester/Main.cpp
src/main/cpp/RLBotInterface/RLBotInterface/Interface.cpp
src/main/cpp/RLBotInterface/RLBotMessages/FileMappings/FileMappings.cpp
src/main/cpp/RLBotInterface/RLBotMessages/MutexUtilities/MutexUtilities.cpp

This commit adds in some minor changes to allow for portability. However, some complex use cases such as those in FileMappings.cpp and Interface.cpp may require entirely different segments of code for Windows and Linux as interoperable functions are missing in many cases.

Minor changes for portability

---

README.md

Add Discord badge to README.md

---

src/main/java/rlbot/gamestate/DesiredVector3.java
src/main/java/rlbot/manager/BotManager.java

Also fixes a minor error in DesiredVector3.java

Allow Java bots to specify their Refresh Rate

---

src/main/cs/RLBotDotNet/RLBotDotNet/Interface/RLBotInterface.cs
src/main/cs/RLBotDotNet/RLBotDotNet/Manager/BotManager.cs
src/main/cs/RLBotDotNet/RLBotDotNet/Properties/AssemblyInfo.cs
src/main/cs/RLBotDotNet/RLBotDotNet/RLBotDotNet.nuspec
src/test/cs/TestBot/Program.cs

Adds a new contructor so old bots do not break,

Add option to dynamically fetch new packets.

---

build.gradle
src/main/java/rlbot/manager/BotManager.java

This is intended to fix https://github.com/RLBot/RLBot/issues/460

Fixing bug where java frame urgency can become highly negative.

---

src/main/python/rlbot/parsing/agent_config_parser.py

The opening brackets shall have their closing brethren once more.

Solved the mystery of the disappearing parenthesis

---

src/main/python/rlbot/botmanager/bot_manager.py
src/main/python/rlbot/botmanager/bot_manager_flatbuffer.py
src/main/python/rlbot/botmanager/bot_manager_independent.py
src/main/python/rlbot/botmanager/bot_manager_struct.py

This is not needed anymore as we validate that all cars are in packet.
This allows us to load custom maps without goals.

Deleted check for field goal.

---

src/main/python/rlbot/agents/base_agent.py
src/main/python/rlbot/utils/structures/game_data_struct_autocomplete.py
src/test/python/agents/atba/atba.py

Works nicely in intellij in atba.py. Once this is deployed, I intend to change the imports in RLBotPythonExample so that new botmakers can get the benefit.
I don't believe there's any performance penalty for using false type hints like this.

Trying to support autocomplete for the game tick packet in python.

---

src/main/python/rlbot/botmanager/bot_manager.py

A simple tweak so that we're not checking for the modification times, of multiple files in some cases, every tick.

Don't check if hot reload is necessary every tick.

---

src/main/python/rlbot/utils/logging_utils.py

Faster getframe alternative for get_logger()

---

runner.bat
runner_gui.bat
src/main/python/rlbot/matchconfig/psyonix_config.py

Also, correct the spacing at the start of the Allstar's names

Don't use the same Psyonix preset multiple times

---

src/main/python/rlbot/agents/hivemind/drone_agent.py
src/main/python/rlbot/agents/hivemind/python_hivemind.py
src/main/python/rlbot/agents/hivemind/subprocess_hivemind.py

Explanation for how it works is on my wiki: https://github.com/ViliamVadocz/Hivemind/wiki
Plans for future:
- Add other languages
- Make hot-reloading work
- Add more in-depth explanations to the wiki
Known issue:
- If you start a match without stopping first the original helper process will not be killed and you will get ghost inputs. This can be spotted by looking at the percentages (200%, etc.)
This issue is resolved with my [PR to RLBotGUI](https://github.com/RLBot/RLBotGUI/pull/64).
---
The rust portion is in this PR: https://github.com/RLBot/rlbot-rust/pull/28

Python and Rust Hiveminds

---

README.md

Also changed the C# example description to mention C# first, since that's what most people are going to be looking at if they're using a .NET language.

Adding new shields to README

---

src/main/python/rlbot/setup_manager.py

This allows mac users (and hopefully linux users) to run the q and r commands in the console. Previously, this was windows only.

r and q commands for mac (and linux?)

---

src/main/python/rlbot/agents/rlbot_runnable.py
src/main/python/rlbot/parsing/bot_config_bundle.py
src/main/python/rlbot/utils/requirements_management.py
src/main/python/rlbot/version.py
src/main/python/setup.py

I intend to modify RLBotGUI to leverage this new functionality and show little warnings when a package is missing.

Adding suppport for requirements.txt files in bots and scripts.

---

src/main/python/rlbot/botmanager/bot_manager_struct.py

I put Botimus, Beast from the East, SkyBot and Kamael in the game, and they're all still rendering fine.

Calling begin_rendering and end_rendering on behalf of python bots.

---

src/main/python/rlbot/setup_manager.py

Please view line 212, idk what I should put there

Add support for the Epic Games Launcher

---

setup_mac.sh

To bring it in line with setup.sh

Removed unnecessary line from setup_mac.sh

---

src/main/python/rlbot/socket/socket_manager.py
src/main/python/rlbot/socket/socket_manager_asyncio.py
src/main/python/rlbot/version.py
src/test/python/agents/standalone/requirements.txt

I'm trying to make a little python script that passes updates to a websocket, and I needed a version of the relay like this. I think it would be useful to others.

Making an asyncio version of the socket manager.

---

src/main/python/rlbot/agents/standalone/standalone_bot.py

- Add a sentence about where to find out more concerning command line arguments
- Fix typo

Fix the doc-string for StandaloneBot

---

src/main/flatbuffers/rlbot.fbs
src/main/python/rlbot/parsing/match_settings_config_parser.py

Shoutout to tarehart for making possible to add this in the open source part.

Add DFHStadium_Circuit

---

src/main/python/rlbot/gamelaunch/epic_launch.py
src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/version.py

Our `webbrowser.open( 'com.epicgames.launcher://apps/Sugar?action=launch&silent=true')` technique isn't working anymore, but this new code works for me.
Hopefully fixes https://github.com/RLBot/RLBotGUI/issues/174
I'm also making a small change to the way we kill processes, sending SIGTERM ahead of time so they have a chance to clean up.

Fix for Rocket League startup on Epic Games Launcher.

---

src/main/python/rlbot/setup_manager.py

When we send sigterm to a process, the children tend to survive as orphans even when the parent dies. Then code after that which was trying to iterate through the children was doing nothing because the parents are already dead, and the children escape.
Now we make a list of all the children before sending sigterm, and get them all.
I'm sending sigterm in a pre-order recursive manner so parents have a chance to deal with their children somehow before I do.

Improving the way setup manager kills processes.

---

src/main/python/rlbot/setup_manager.py
src/main/python/rlbot/utils/structures/game_interface.py

If someone could please test this in Windows for me that would be awesome haha, just start a match and if it works then it should be good. I just want to make sure that I didn't break anything for you Windows folk.
I haven't fixed anything with Proton, just fixed the breaking changes introduced in 1.53.0.

Fix Linux launch

---

src/main/python/rlbot/csv/items.csv
src/main/python/rlbot/csv/items.py
src/main/python/setup.py

This is for RLBot/RLBotPack#235

Add open_csv for loading the game items

---

src/main/python/rlbot/setup_manager.py

This fixes an error that I was encountering in my testing.

Make sure stdin is never inherited when spawning subprocess
